FROM jefflaplante/php-fpm

RUN apk add postfix bash rsync --no-cache && \
    adduser -D mturkcrowd && \
    mkdir -p /var/www/mtc

COPY main.cf /etc/postfix/main.cf

COPY start.sh /start.sh

COPY copy.sh /copy.sh

CMD ["/start.sh"]
