FROM ubuntu:15.10

RUN apt-get update && apt-get install -y vim rsync php5 php5-common php5-cli php5-fpm \
    php5-curl php5-imagick php5-gd php5-mysql php5-readline php5-memcached \
    php5-memcache php5-redis \
    imagemagick-common imagemagick \
    --no-install-recommends && rm -r /var/lib/apt/lists/* &&\
    mkdir -p /var/www/mtc && \
    mkdir /run/php 
    
COPY html/ /var/www/html

COPY www.conf /etc/php5/fpm/pool.d/www.conf

COPY setup.sh /usr/local/bin/setup.sh

CMD ["php5-fpm"]
