/*!
 * Copyright 2015, ThemesCorp All Rights Reserved.
 * http://ThemesCorp.com
 * This file may not be redistributed in whole or significant part without prior consent from ThemesCorp.
 * Version: 1.00 - Script create by ThemesCorp
 */
$(document).ready(function(){var c,f;try{c=document.getElementsByClassName("mainContent")[0],f=window.getComputedStyle(c).marginRight}catch(k){return}var g=function(){$.setCookie("sidebar",!0);$(".mainContent").animate({marginRight:f},"slow",function(){$(".sidebar").fadeTo("slow",1,function(){$("div.mainContent").removeClass("no_sidebar");$("div.sidebar_mini").removeClass("sidebar_expand");$("div.sidebar").show()})})},h=function(){$.setCookie("sidebar",!1);$("div.sidebar").fadeTo("slow",0,function(){$("div.mainContent").animate({marginRight:0},
"slow");$("div.mainContent").addClass("no_sidebar");$("div.sidebar_mini").addClass("sidebar_expand");$("div.sidebar").hide()})},d=!1;c=function(){var a=$("div.sidebar"),b=$("div.mainContent"),c=$("#navigation");if(!d&&a.is(":visible")){d=!0;b.offset().top?b.offsetTop=b.offset().top:b.offsetTop=b[0].offsetTop;b.offset().left?b.offsetLeft=b.offset().left:b.offsetLeft=b[0].offsetLeft;if(a.height()>=$(b).height()||b.offsetLeft+$(b).width()>a.offset().left)return a.css({position:"initial",top:"initial",
right:"initial"}),!(d=!1);if(0==$(window).scrollTop())a.css({position:"initial",top:"initial",right:"initial"});else{a.css("position","fixed");a.css("right",b.offsetLeft);if(0<b.offsetTop-$(document).scrollTop()){var e=b.offsetTop-$(document).scrollTop();10>e&&(e=10);a.css("top",e)}else a.css("top",10);(c.hasClass("sticky")||c.parent().hasClass("is-sticky"))&&parseInt(a.css("top"))<c.height()+10&&a.css("top",c.height()+10);a.offset().top>b.offsetTop+$(b).height()-a.height()&&a.css("top",$("div.breadBoxBottom").offset().top-
a.height()-$(window).scrollTop())}return!(d=!1)}};$("div.sidebar_mini a").length&&("false"==$.getCookie("sidebar")&&($("div.mainContent").addClass("no_sidebar"),$("div.sidebar_mini").addClass("sidebar_expand"),$("div.sidebar").css("opacity",0),$("div.sidebar").hide()),$("div.sidebar_mini a").click(function(a){$("div.mainContent").hasClass("no_sidebar")?g():h();a.stopPropagation();a.preventDefault()}));$("div.sidebar").hasClass("fixed")||($(document).scroll(c),$(window).resize(c),c())});