<?php if (!class_exists('XenForo_Application', false)) die(); $__output = '';
if ($context == ('setup'))
{
$__output .= '
	';
$this->addRequiredExternal('js', 'js/jquery/jquery.qrcode-0.12.0.min.js');
$__output .= '
	<dl class="ctrlUnit">
		<dt>' . 'Setup' . ':</dt>
		<dd>
			' . 'To receive verification codes via a phone app, you must first install a code-generating app such as <a href="https://www.authy.com/users" target="_blank">Authy</a> or <a href="https://support.google.com/accounts/answer/1066447?hl=en" target="_blank">Google Authenticator</a> on your phone.<br />
			<br />
			Once you have done this, you will need to scan the QR code below into the app and enter the generated code below to confirm.' . '
			<div style="text-align: center"><span id="TotpQrCode" style="display: inline-block; background: white; padding: 12px"></span></div>
			' . 'Alternatively, you may enter the secret into the app directly: ' . htmlspecialchars($secret, ENT_QUOTES, 'UTF-8') . '' . '
		</dd>
	</dl>
	<script>
	$(function()
	{
		var $el = $(\'#TotpQrCode\');
		$el.qrcode({
			text: \'' . XenForo_Template_Helper_Core::jsEscape(htmlspecialchars($otpUrl, ENT_QUOTES, 'UTF-8'), 'double') . '\'
		});
	});
	</script>
';
}
else
{
$__output .= '
	<p>' . 'Please enter the verification code generated by the app on your phone.' . '</p>
';
}
$__output .= '

<dl class="ctrlUnit">
	<dt><label for="ctrl_totp_code">' . 'Verification Code' . ':</label></dt>
	<dd>
		<input type="text" name="code" id="ctrl_totp_code" class="textCtrl" />
	</dd>
</dl>';
